# @author: rahul
# wifi password: jaykol12390
image: node:8.9.0


stages:
  - build
  - release
  - review
  - deploy
  # - pre-production

variables:
  CONTAINER_IMAGE: ${CI_REGISTRY_IMAGE}/${CI_BUILD_REF_NAME}:${CI_BUILD_REF}
  CONTAINER_IMAGE_LATEST: ${CI_REGISTRY_IMAGE}/${CI_BUILD_REF_NAME}:latest
  CONTAINER_IMAGE_UNTAGGED: ${CI_REGISTRY_IMAGE}/${CI_BUILD_REF_NAME}
  DOCKER_DRIVER: overlay2

  KUBECONFIG: /etc/deploy/config
  # STAGING_NAMESPACE: app-stage
  # PRODUCTION_NAMESPACE: app-prod
  #
  # APP_PATH: /go/src/gitlab.example.com/librerio/libr_files
  # POSTGRES_USER: gorma
  # POSTGRES_DB: test-${CI_BUILD_REF}
  # POSTGRES_PASSWORD: gorma

# before_script:

cache:
  paths:
    - node_modules/
    - build/

build:
  stage: build
  artifacts:
    paths:
      - node_modules/
      - build/
  script:
    - npm install -g yarn
    - yarn install
    - yarn run build --release
  only:
    - development
    - qa
    - master

production:
  type: deploy
  stage: deploy
  image: ruby:latest
  script:
    - cd build
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - export HEROKU_API_KEY=81052ce8-b711-4969-b53c-d94081778883
    - dpl --provider=heroku --app=pose3d --api-key=$HEROKU_API_KEY
  only:
    - master

# release:
#   stage: release
#   image: docker:latest
#   services:
#     - docker:dind
#   variables:
#     DOCKER_DRIVER: "overlay2"
#     DOCKER_HOST: "tcp://localhost:2375"
#   before_script:
#     - docker info
#   script:
#     - docker login -u gitlab-ci-token -p ${CI_BUILD_TOKEN} ${CI_REGISTRY}
#     - docker build -t ${CONTAINER_IMAGE} .
#     - docker tag ${CONTAINER_IMAGE} ${CONTAINER_IMAGE_LATEST}
#     - docker push ${CONTAINER_IMAGE}
#     - docker push ${CONTAINER_IMAGE_LATEST}
#   only:
#     - development
#     - qa
#     - master

